
- name: install strongswan
  apt:
    name: "{{item}}"
    state: present
  loop: "{{debian_package}}"


- name: Enable Kernel Packet Forwarding
  bolckinfile:
    path: /etc/systcl.conf
    block: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding = 1
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv4.conf.all.send_redirects = 0
  notify: save change

- name: edit ipsec config file
  template:
    src: templates/ipsec.conf.j2
    dest: /etc/ipsec.conf

- name: edit ipsec secret file
  template:
    src: templates/ipsec.secrets.j2
    dest:  /etc/ipsec.secrets

- name: start and enable strongswan service
  service:
    name: "{{debian_service}}"
    state: started
    enabled: yes

      





    

